pipeline {
  agent any
  tools {
    maven "M3"
    jdk "JDK11"
  }
  
  environment {
    AWS_CREDENTIAL_NAME = "awsEcrCredential"
    AWS_ACCOUNT_ID = "257307634175"
    REGION = "ap-northeast-2"
    Docker_IMAGE_NAME="aws07-spring-petclinic"
    Docker_TAG="1.0"
    ECR_REPOSITORY = "${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com"
    ECR_DOCKER_IMAGE = "${ECR_REPOSITORY}/${DOCKER_IMAGE_NAME}"
    ECR_DOCKER_TAG = "${DOCKER_TAG}"
    }
  
  stages {
    stage('Git fetch') {
      steps {
        echo 'Git fetch'
        git url: 'https://github.com/sjh9397/spring-petclinic.git/',
          branch: 'main', credentialsId: 'gitCrednetial'
    }
  }
     stage('Maven Build') {
      steps {
        echo 'Maven Build'
        sh 'mvn -Dmaven.test.failure.ignore=true clean package'
    }
  }
     stage('Docker Image') {
      steps {
        echo 'Docker Image'
        dir("${env.WORKSPACE}"){
         sh 'docker build -t aws07-spring-petclinic:1.0 . '  
      }
    }
  }
     stage('Image push') {
      steps {
        echo 'Image push'
    }
  }
     stage('Codedeploy Workload') {
      steps {
        echo 'Codedeploy Workload'
    }
  }
 }
}
