pipeline {
  agent any
  
  stages {
    stage('Git fatch') {
      steps {
        echo 'Git fatch'
        git url: 'https://github.com/sjh9397/spring-petclinic.git/',
          branch: 'main', credentialsId: 'gitCrednetial'
    }
  }
     stage('Mvn Build') {
      steps {
        echo 'Maven Build'
    }
  }
     stage('Docker Image') {
      steps {
        echo 'Docker Image'
    }
  }
     stage('Image push') {
      steps {
        echo 'Image push'
    }
  }
     stage('Codedeploy Workload') {
      steps {
        echo 'Codedeploy Workload'
    }
  }
 }
}
